import 'package:flutter/material.dart';

enum VoiceGender {
  male,
  female,
  neutral,
}

enum PersonaLanguage {
  english,
  arabic,
}

class VoicePersona {
  final String id;
  final String name;
  final String nameArabic;
  final VoiceGender gender;
  final PersonaLanguage language;
  final String tag;
  final String tagArabic;
  final String description;
  final String descriptionArabic;
  final double pitch;
  final double rate;
  final IconData icon;
  final Color accentColor;
  final List<String> preferredSystemVoices;

  const VoicePersona({
    required this.id,
    required this.name,
    required this.nameArabic,
    required this.gender,
    this.language = PersonaLanguage.english,
    required this.tag,
    required this.tagArabic,
    required this.description,
    required this.descriptionArabic,
    required this.pitch,
    required this.rate,
    required this.icon,
    required this.accentColor,
    this.preferredSystemVoices = const [],
  });

  static const List<VoicePersona> englishPersonas = [
    // --- MEN VOICES ---
    VoicePersona(
      id: 'male_deep',
      name: 'Alexander',
      nameArabic: 'ألكسندر',
      gender: VoiceGender.male,
      language: PersonaLanguage.english,
      tag: 'Deep Studio Narrator',
      tagArabic: 'صوت استوديو عميق',
      description: 'Authoritative, resonant, BBC-quality deep baritone',
      descriptionArabic: 'نبرة رجالية فصيحة ورصينة ومتقنة بمخارج واضحة',
      pitch: 0.94,
      rate: 1.00,
      icon: Icons.record_voice_over_rounded,
      accentColor: Color(0xFF3B82F6),
      preferredSystemVoices: [
        'google uk english male',
        'uk english male',
        'english male',
        'mark',
        'guy',
        'george',
        'brian',
        'oliver',
        'david',
        'male',
      ],
    ),
    VoicePersona(
      id: 'male_warm',
      name: 'Marcus',
      nameArabic: 'ماركوس',
      gender: VoiceGender.male,
      language: PersonaLanguage.english,
      tag: 'Warm Storyteller',
      tagArabic: 'راوٍ دافئ ومتزن',
      description: 'Balanced, conversational, natural everyday narration',
      descriptionArabic: 'صوت رجالي طبيعي بنبرة دافئة وانسيابية',
      pitch: 1.00,
      rate: 1.00,
      icon: Icons.person_rounded,
      accentColor: Color(0xFF0EA5E9),
      preferredSystemVoices: [
        'google uk english male',
        'google us english',
        'mark',
        'guy',
        'daniel',
        'brian',
        'alex',
        'david',
        'male',
      ],
    ),
    VoicePersona(
      id: 'male_crisp',
      name: 'Elijah',
      nameArabic: 'إيليا',
      gender: VoiceGender.male,
      language: PersonaLanguage.english,
      tag: 'Energetic Presenter',
      tagArabic: 'مقدم إذاعي حيوي',
      description: 'Clear, dynamic and enthusiastic modern male voice',
      descriptionArabic: 'صوت رجالي شاب مفعم بالحيوية والوضوح',
      pitch: 1.03,
      rate: 1.04,
      icon: Icons.campaign_rounded,
      accentColor: Color(0xFF6366F1),
      preferredSystemVoices: [
        'google uk english male',
        'google us english',
        'mark',
        'daniel',
        'david',
        'male',
      ],
    ),

    // --- WOMEN VOICES ---
    VoicePersona(
      id: 'female_elegant',
      name: 'Victoria',
      nameArabic: 'فيكتوريا',
      gender: VoiceGender.female,
      language: PersonaLanguage.english,
      tag: 'Studio Executive',
      tagArabic: 'صوت نسائي ملكي راقٍ',
      description: 'Smooth, articulate, executive BBC-style narration',
      descriptionArabic: 'نبرة نسائية فصيحة ورخيمة فائقة النقاء',
      pitch: 1.00,
      rate: 0.98,
      icon: Icons.voice_chat_rounded,
      accentColor: Color(0xFFEC4899),
      preferredSystemVoices: [
        'google uk english female',
        'uk english female',
        'google us english',
        'victoria',
        'hazel',
        'susan',
        'catherine',
        'jenny',
        'aria',
        'samantha',
        'zira',
        'female',
      ],
    ),
    VoicePersona(
      id: 'female_bright',
      name: 'Emma',
      nameArabic: 'إيما',
      gender: VoiceGender.female,
      language: PersonaLanguage.english,
      tag: 'Bright & Engaging',
      tagArabic: 'صوت نسائي مشرق ومبهج',
      description: 'Lively, friendly, crisp and engaging speech',
      descriptionArabic: 'صوت نسائي بهيج وواضح بطابع حديث',
      pitch: 1.04,
      rate: 1.00,
      icon: Icons.face_3_rounded,
      accentColor: Color(0xFFF43F5E),
      preferredSystemVoices: [
        'google us english',
        'google uk english female',
        'jenny',
        'aria',
        'karen',
        'samantha',
        'zira',
        'female',
      ],
    ),
    VoicePersona(
      id: 'female_gentle',
      name: 'Sophia',
      nameArabic: 'صوفيا',
      gender: VoiceGender.female,
      language: PersonaLanguage.english,
      tag: 'Gentle & Calming',
      tagArabic: 'صوت نسائي هادئ ومريح',
      description: 'Soft, relaxing, mindful feminine cadence',
      descriptionArabic: 'نبرة نسائية ناعمة ومريحة ومريحة للأعصاب',
      pitch: 0.98,
      rate: 0.95,
      icon: Icons.spa_rounded,
      accentColor: Color(0xFFA855F7),
      preferredSystemVoices: [
        'google uk english female',
        'google us english',
        'sophia',
        'samantha',
        'zira',
        'female',
      ],
    ),

    // --- SPECIAL EFFECTS ---
    VoicePersona(
      id: 'cyber_bot',
      name: 'Titan-9',
      nameArabic: 'تيتان-9',
      gender: VoiceGender.neutral,
      language: PersonaLanguage.english,
      tag: 'Cybernetic AI',
      tagArabic: 'ذكاء اصطناعي سيبراني',
      description: 'Futuristic high-tech neural synthesizer tone',
      descriptionArabic: 'صوت ذكاء اصطناعي متطور ذو طابع مستقبلي',
      pitch: 0.88,
      rate: 1.08,
      icon: Icons.smart_toy_rounded,
      accentColor: Color(0xFF10B981),
      preferredSystemVoices: [
        'google uk english male',
        'google us english',
        'david',
      ],
    ),
  ];

  static const List<VoicePersona> arabicPersonas = [
    // --- أصوات الرجال بالعربية ---
    VoicePersona(
      id: 'ar_male_deep',
      name: 'Tariq',
      nameArabic: 'طارق',
      gender: VoiceGender.male,
      language: PersonaLanguage.arabic,
      tag: 'Deep Arabic Reader',
      tagArabic: 'صوت رجالي وقور ورخيم',
      description: 'Authoritative, resonant classical Arabic male reader',
      descriptionArabic: 'صوت عربي فصيح بنبرة رخيمة ووقورة مناسب للشعر والأخبار والكتب',
      pitch: 0.94,
      rate: 0.98,
      icon: Icons.record_voice_over_rounded,
      accentColor: Color(0xFF3B82F6),
      preferredSystemVoices: [
        'ar',
        'arabic',
        'tarik',
        'maged',
        'hamed',
        'shakir',
        'naayf',
        'google uk english male',
        'mark',
      ],
    ),
    VoicePersona(
      id: 'ar_male_warm',
      name: 'Omar',
      nameArabic: 'عمر',
      gender: VoiceGender.male,
      language: PersonaLanguage.arabic,
      tag: 'Warm Arabic Narrator',
      tagArabic: 'راوٍ عربي طبيعي وودود',
      description: 'Natural everyday Arabic male voice with conversational cadence',
      descriptionArabic: 'صوت رجالي عربي طبيعي ودافئ لقراءة القصص والروايات والمقالات',
      pitch: 1.00,
      rate: 1.00,
      icon: Icons.person_rounded,
      accentColor: Color(0xFF0EA5E9),
      preferredSystemVoices: [
        'ar',
        'arabic',
        'maged',
        'tarik',
        'hamed',
        'naayf',
        'mark',
        'google uk english male',
      ],
    ),

    // --- أصوات النساء بالعربية ---
    VoicePersona(
      id: 'ar_female_warm',
      name: 'Fatima',
      nameArabic: 'فاطمة',
      gender: VoiceGender.female,
      language: PersonaLanguage.arabic,
      tag: 'Articulate Arabic Female',
      tagArabic: 'صوت نسائي فصيح وأصيل',
      description: 'Eloquent, classical feminine Arabic voice with clear diction',
      descriptionArabic: 'صوت نسائي عربي فصيح ورخيم بمخارج حروف دقيقة ومتمكنة',
      pitch: 1.01,
      rate: 0.98,
      icon: Icons.voice_chat_rounded,
      accentColor: Color(0xFFEC4899),
      preferredSystemVoices: [
        'ar',
        'arabic',
        'zeina',
        'salma',
        'laila',
        'mariam',
        'hoda',
        'sana',
        'google uk english female',
        'google us english',
      ],
    ),
    VoicePersona(
      id: 'ar_female_bright',
      name: 'Mariam',
      nameArabic: 'مريم',
      gender: VoiceGender.female,
      language: PersonaLanguage.arabic,
      tag: 'Bright Arabic Female',
      tagArabic: 'صوت نسائي نضر ومشرق',
      description: 'Lively, friendly and cheerful modern Arabic female voice',
      descriptionArabic: 'صوت نسائي عربي مبهج ومفعم بالحيوية والتفاؤل والانطلاق',
      pitch: 1.04,
      rate: 1.00,
      icon: Icons.face_3_rounded,
      accentColor: Color(0xFFF43F5E),
      preferredSystemVoices: [
        'ar',
        'arabic',
        'zeina',
        'salma',
        'mariam',
        'laila',
        'sana',
        'google us english',
        'google uk english female',
      ],
    ),

    // --- صوت إلكتروني عربي ---
    VoicePersona(
      id: 'ar_cyber_bot',
      name: 'Titan AR',
      nameArabic: 'المعالج الذكي',
      gender: VoiceGender.neutral,
      language: PersonaLanguage.arabic,
      tag: 'Arabic AI Synth',
      tagArabic: 'ذكاء اصطناعي باللغة العربية',
      description: 'High-tech synthetic futuristic Arabic voice',
      descriptionArabic: 'صوت ذكاء اصطناعي إلكتروني متطور وفصيح باللغة العربية',
      pitch: 0.88,
      rate: 1.08,
      icon: Icons.smart_toy_rounded,
      accentColor: Color(0xFF10B981),
      preferredSystemVoices: [
        'ar',
        'arabic',
        'google uk english male',
      ],
    ),
  ];

  static List<VoicePersona> get allPersonas => [
        ...englishPersonas,
        ...arabicPersonas,
      ];
}
